# Generated by Django 3.1.4 on 2020-12-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sentimentVal', models.FloatField(default=9.9)),
                ('picture', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('picture', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='searchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('lyrics', models.TextField()),
                ('sentiment', models.CharField(default='', max_length=120)),
                ('sentimentVal', models.FloatField(default=9.9)),
                ('album', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lyricsAnalysis.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lyricsAnalysis.artist'),
        ),
    ]
