# Generated by Django 3.1.4 on 2020-12-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
