# Generated by Django 3.1.4 on 2020-12-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lyricsAnalysis', '0002_artist_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='searchResult',
        ),
    ]
